### PR TITLE
Change all the imports to github.com/tofuutils/tenv/v2 module path

### LINKED ISSUE #176: go install -v github.com/tofuutils/tenv/cmd/tenv@latest installing version 1
**Describe the bug**
Since you have tagged v2 version of the package, can you also please update go.mod file, with

```
module github.com/tofuutils/tenv/v2
```

To make it go install-able again.

**To Reproduce**
```
$ go install -v github.com/tofuutils/tenv/cmd/tenv@latest
go: downloading github.com/tofuutils/tenv v1.11.19
```

**Expected behavior**

`go install -v github.com/tofuutils/tenv/cmd/tenv/v2@latest` will install latest v2.

**Environment (please complete the following information):**
- OS: any
- tofuenv version: v2.x.x

### PR DESCRIPTION
**Pull request by kron4eg**
Fixes #176

### CODE REVIEW

File: versionmanager/retriever/terragrunt/terragruntretriever.go [hunk 1]
```diff
@@ -103,12 +104,12 @@ func (r TerragruntRetriever) InstallRelease(versionStr string, targetPath string
 		return err
 	}
 
-	err = os.MkdirAll(targetPath, 0755)
+	err = os.MkdirAll(targetPath, 0o755)
```
Comment (kvendingoldo) [inline versionmanager/retriever/terragrunt/terragruntretriever.go:107]: why is it 0o755?

Comment (kron4eg) [reply versionmanager/retriever/terragrunt/terragruntretriever.go:107]: It's automatically changed on save in vscode. See more https://github.com/golang/go/issues/33363.
